{{- define "hpa.template" -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}
  minReplicas: {{ .hpa.minReplicas }}
  maxReplicas: {{ .hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .hpa.targetCPUUtilizationPercentage }}
---
{{- end -}}

{{- template "hpa.template" (dict "name" "loginweb" "hpa" .Values.hpa.loginweb) -}}
{{- template "hpa.template" (dict "name" "boardweb" "hpa" .Values.hpa.boardweb) -}}
{{- template "hpa.template" (dict "name" "mainweb" "hpa" .Values.hpa.mainweb) -}}
{{- template "hpa.template" (dict "name" "memberweb" "hpa" .Values.hpa.memberweb) -}}